version: "3.8"
services:
  web:
    build:
      context: .
    volumes:
      - ./app:/app
      - ./data:/app/data
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev