name: "WoLManager"
services:
  web:
    build:
      context: .
    volumes:
      - ../app:/app
      - ../data:/data
      - ../docker:/app/docker
    ports:
      - "3000:3000"
      - "35729:35729"
    environment:
      - NODE_ENV=development
    command: npm run dev